name: Test build

on:
  pull_request:
    branches: [ master ]

jobs:
    deploy:
        name: Deploy to Cloud Run
        runs-on: ubuntu-latest
        steps:

        - name: Checkout repository
          uses: actions/checkout@v2

        - id: 'auth'
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v0'

        - name: 'Output default GCP credentials to file'
          run: printf '${{ secrets.GCP_CREDENTIALS }}' >> key.json

        - name: Build Docker image
          run: docker build . -t ${{ secrets.GCP_APP_NAME }}

        - name: Test Docker image
          run: docker run ${{ secrets.GCP_APP_NAME }} -e GOOGLE_APPLICATION_CREDENTIALS='key.json' sh -c "go test -v"